// angular-app/angular-app/src/spa.ts
import 'zone.js';
import { NgZone } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { singleSpaAngular } from 'single-spa-angular';
import { AppComponent } from './app/app.component';

const lifecycles = singleSpaAngular({
  bootstrapFunction: () => bootstrapApplication(AppComponent),
  template: '<app-root></app-root>',
  NgZone,
  domElementGetter: () => document.getElementById('single-spa-application'),
});

export const { bootstrap, mount, unmount } = lifecycles;

// coffee-app/src/spa.jsx
import React from 'react';
import ReactDOM from 'react-dom';
import singleSpaReact from 'single-spa-react';
import App from './App.coffee';

const lifecycles = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: App,
  domElementGetter: () => document.getElementById('single-spa-application'),
  errorBoundary(err) {
    return <div>Coffee App failed to load: {err.message}</div>;
  },
});

export const { bootstrap, mount, unmount } = lifecycles;
